# fly.toml app configuration file generated for eindjeboss on 2023-04-26T12:43:14+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "eindjeboss"
primary_region = "ams"
kill_signal = "SIGINT"
kill_timeout = 5

[[mounts]]
  source = "eindjeboss_data_machines"
  destination = "/eindjeboss_files"
  processes = ["app"]
