name: Gitleaks
on:
  push:
    branches:
      - main
jobs:
  scan:
      name: gitleaks
      runs-on: ubuntu-latest
      steps:
        - uses: gitleaks/gitleaks-action@v2.3.2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}